from PyQt5 import QtCore, QtGui, QtWidgets

class SettingsDialog(QtWidgets.QDialog):
    def __init__(self, base, parent=None):
        super().__init__(parent)
        self.ui = base
        self.setModal(True)
        self.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)

        self.setupUi()

        self.show()
        self.exec_()
        self.ui.threadpool.setMaxThreadCount(int(self.maxThreads.text()))
        self.ui.setCounters(int(self.counters.text())) if int(self.counters.text()) != len(self.ui.counters) else ""

    def setupUi(self):
        self.resize(464, 119)
        self.setWindowTitle("Settings")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.maxThreadsLabel = QtWidgets.QLabel(self.frame)
        self.maxThreadsLabel.setObjectName("maxThreadsLabel")
        self.horizontalLayout_2.addWidget(self.maxThreadsLabel)
        self.maxThreads = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxThreads.sizePolicy().hasHeightForWidth())
        self.maxThreads.setSizePolicy(sizePolicy)
        self.maxThreads.setMinimum(1)
        self.maxThreads.setMaximum(1000)
        self.maxThreads.setProperty("value", self.ui.threadpool.maxThreadCount())
        self.maxThreads.setObjectName("maxThreads")
        self.horizontalLayout_2.addWidget(self.maxThreads)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.countersLabel = QtWidgets.QLabel(self.frame)
        self.countersLabel.setObjectName("countersLabel")
        self.horizontalLayout.addWidget(self.countersLabel)
        self.counters = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counters.sizePolicy().hasHeightForWidth())
        self.counters.setSizePolicy(sizePolicy)
        self.counters.setMinimum(1)
        self.counters.setMaximum(1000)
        self.counters.setProperty("value", len(self.ui.counters))
        self.counters.setObjectName("counters")
        self.horizontalLayout.addWidget(self.counters)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.maxThreadsLabel.setText("Maximum Thread Count")
        self.countersLabel.setText("Counters")

        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)
        QtCore.QMetaObject.connectSlotsByName(self)